#!/bin/bash

N=$(grep "d:" params.yaml|cut -f2 -d' ')

# Will add B times the number B
cat result3/dat|sed "s/$/ $(yes $N|head -n $N|tr -d '\n')/" > result4/dat
#for FILE in result?/dat; do ls -l $FILE; sed 's/^/\t/' $FILE; done
